version: '3'
services:
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=user
    #   - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: 
